<a href="https://colab.research.google.com/github/Mattapalli73/Pytorch/blob/main/Automatic%20Differentiation%20with%20torch.autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import torch
import numpy as np
from torch.utils.data import dataloader

input=torch.ones(5)
print(input)

output=torch.zeros(3)
print(output)

par_w=torch.randn(5,3,requires_grad=True)
print(par_w)

par_b=torch.randn(3,requires_grad=True)
print(par_b)

output_z=torch.matmul(input,par_w)+par_b
print(output_z)

Loss=torch.nn.functional.binary_cross_entropy_with_logits(output_z,output)

print('Gradient Function for output_z:',output_z.grad_fn)
print('Gradient Function for Loss:',Loss.grad_fn)

Loss.backward(retain_graph=True)
print('the Gradient of par_w is :',par_w.grad)
print('the Gradient of par_b is :',par_b.grad)
Loss.backward(retain_graph=True)
print('the Gradient of par_w is :',par_w.grad)
print('the Gradient of par_b is :',par_b.grad)
Loss.backward(retain_graph=True)
print('the Gradient of par_w is :',par_w.grad)
print('the Gradient of par_b is :',par_b.grad)

print('Diabling the Gradint Function')

output_z=torch.matmul(input,par_w)+par_b
print(output_z.requires_grad)

with torch.no_grad():
  output_z=torch.matmul(input,par_w)+par_b
print(output_z.requires_grad)

print('Another way of Diabling the Gradint Function')
output_z=torch.matmul(input,par_w)+par_b
print(output_z.requires_grad)
z_detach=output_z.detach()
print(z_detach.requires_grad)





tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
tensor([[ 0.9029, -0.1989,  0.6929],
        [-1.1950,  0.7737,  0.4192],
        [ 2.2198, -0.5059, -0.8130],
        [ 0.7687,  0.5505,  0.2762],
        [ 0.4306,  0.2674,  0.9799]], requires_grad=True)
tensor([-1.3544, -1.2380,  1.3469], requires_grad=True)
tensor([ 1.7724, -0.3512,  2.9021], grad_fn=<AddBackward0>)
Gradient Function for output_z: <AddBackward0 object at 0x7fc1cc205110>
Gradient Function for Loss: <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fc1ccc733d0>
the Gradient of par_w is : tensor([[0.2849, 0.1377, 0.3160],
        [0.2849, 0.1377, 0.3160],
        [0.2849, 0.1377, 0.3160],
        [0.2849, 0.1377, 0.3160],
        [0.2849, 0.1377, 0.3160]])
the Gradient of par_b is : tensor([0.2849, 0.1377, 0.3160])
the Gradient of par_w is : tensor([[0.5698, 0.2754, 0.6320],
        [0.5698, 0.2754, 0.6320],
        [0.5698, 0.2754, 0.6320],
        [0.5698, 0.2754, 0.6320],
        [0.5698, 0.2754, 0.6320]])
the Gra