<a href="https://colab.research.google.com/github/Mattapalli73/Pytorch/blob/main/Basic%20tensor%20manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import torch
from torch import nn

print('Basic Tensor Manipulations')

#creating a matrix with diagonal Eleents as 1's and the data type and size
x=torch.eye(5,5)
print(x)
print(x.size())
print(x.dtype)

#assigning the data type int
i=torch.ones((2,2),dtype=torch.int16)
print(i)

#Seeding 

torch.manual_seed(155)
rand1=torch.rand(3,3)
print(rand1)

rand2=torch.rand(3,3)
print(rand2)

torch.manual_seed(155)
rand3=torch.rand(3,3)
print(rand3)
#adding the two matrix
add12=rand1+rand2
print(add12)
#multiplying the two matrix
mul=rand2*rand3
print('multiplication result is:',mul)
#multiplying the tensor with 10
result=x*10
print('the result is ',result)

result2=torch.ones(1,2)*10
print(result2)

#some random oprerations

a1=torch.rand(2,2)-0.5*2
print(a1)
#absolute Value
a2=torch.abs(a1)
print(a2)
#inverse
a3=torch.asin(a1)
print(a3)
#determinant
print(torch.det(rand1))
#Singular value decomposition
print(torch.svd(rand1))
#Average and std deviation
print(torch.std_mean(a1))
#max value
print(torch.max(a1))

Basic Tensor Manipulations
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
torch.Size([5, 5])
torch.float32
tensor([[1, 1],
        [1, 1]], dtype=torch.int16)
tensor([[0.9955, 0.9558, 0.8075],
        [0.5049, 0.3254, 0.8290],
        [0.8800, 0.4684, 0.2964]])
tensor([[0.6001, 0.4721, 0.1455],
        [0.4672, 0.3077, 0.0258],
        [0.6270, 0.4559, 0.9807]])
tensor([[0.9955, 0.9558, 0.8075],
        [0.5049, 0.3254, 0.8290],
        [0.8800, 0.4684, 0.2964]])
tensor([[1.5956, 1.4280, 0.9530],
        [0.9721, 0.6330, 0.8548],
        [1.5070, 0.9243, 1.2771]])
multiplication result is: tensor([[0.5974, 0.4513, 0.1175],
        [0.2359, 0.1001, 0.0214],
        [0.5518, 0.2136, 0.2907]])
the result is  tensor([[10.,  0.,  0.,  0.,  0.],
        [ 0., 10.,  0.,  0.,  0.],
        [ 0.,  0., 10.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0.],
        [ 0.,  0.,  0.,  0., 10.]])
tenso